Add missing #include <unistd.h>
Fixes:

    vtuner-simple.c:51:24: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
    vtuner-simple.c:52:19: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
    vtuner-simple.c:53:13: warning: implicit declaration of function ‘usleep’ [-Wimplicit-function-declaration]
    vtuner-simple.c:60:9: warning: implicit declaration of function ‘lseek’ [-Wimplicit-function-declaration]